### ISSUE TITLE
Feature: Implement the endpoints for the simulator

### ISSUE THREAD

**Issue by bitknox** [Lindharden/DevOps#13]
**Describe the solution you'd like**
All endpoints should be implemented as described in: [this file](https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_03/README_TASKS.md)

**Additional context**
This is done when issues #8 #10 #11 #12 are completed

**Comment by nikso-itu** [comment]
Endpoints to create:
 - [ ] `/latest`  uses `GET` to fetch JSON of lates "value".
 - [ ] `/msgs` uses `GET` to fetch JSON of all messages. Return 403 if not authorized. The returned messages should be filterered such that they only show `text`, `pub_date` and `username`. Only show messages which are not flagged.
 - [ ] `/msgs/<username>`  if `GET` then fetch JSON of all messages by user `<username>` (same format as above). If `POST` insert message from `<username>` into DB, and return 204.
 - [ ] `/fllws/<username>` if `GET` fetch JSON of all followers of `<username>`. Should contain all follower usernames. If `POST` and `follow` update `<username>` to follow `follow`. If `POST` and `unfollow` update `<username>` to unfollow `unfollow`.
