### ISSUE TITLE
Feature: Setup application monitoring

### ISSUE THREAD

**Issue by Lindharden** [Lindharden/DevOps#65]
**Describe the solution you'd like**

Implement application monitoring for the following:

- [x] - Number of tweet requests per hour

**Describe alternatives you've considered**
- [ ] - Number of total requests per hour
- [ ] - How long do our database queries take?
- [ ] - How long does some external vendor API takes to respond
- [ ] - How many logins happens throughout the day
- [ ] - Number of faulty requests a day

**Additional context**

We should discuss in plenum what is valuable for us to monitor and if there are additional aspects we should monitor.

**Comment by bitknox** [comment]
Closed by #74
