### ISSUE TITLE
Feature: logging

### ISSUE THREAD

**Issue by Lindharden** [Lindharden/DevOps#81]
**Is your feature request related to a problem? Please describe.**
[https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_08/README_TASKS.md](https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_08/README_TASKS.md)

**Describe the solution you'd like**
deploy an EFK stack as shown in the exercises; but we can also use another logging stack.

It is ideal if we find a way to make the logging infrastructure available also to course responsibles. If we succeed, add the url of our logging dashboard to the "Logging URL" section of the misc_urls.py file. Make it accessible with the same credentials as the monitoring dashboard.

Following must be done:
- [x] - Deploy EFK Stack
- [x] - Make logging infrastructure available to course responsible
- [x] - Add logging url to misc_urls.py file [https://github.com/itu-devops/lecture_notes/blob/master/misc_urls.py](https://github.com/itu-devops/lecture_notes/blob/master/misc_urls.py) 

**Describe alternatives you've considered**
No alternative EFK stack considered as of yet.

**Comment by bitknox** [comment]
Closed by #84
